const ROPSTEN = 'ropsten'
const RINKEBY = 'rinkeby'
const KOVAN = 'kovan'
const MAINNET = 'mainnet'
const LOCALHOST = 'localhost'
const GOERLI = 'goerli'
const TOMO_MAINNET = 'tomo_mainnet'
const TOMO_TESTNET = 'tomo_testnet'

const MAINNET_CODE = 1
const ROPSTEN_CODE = 3
const RINKEBY_CODE = 4
const KOVAN_CODE = 42
const GOERLI_CODE = 5
const TOMO_MAINNET_CODE = 88
const TOMO_TESTNET_CODE = 89

const ROPSTEN_DISPLAY_NAME = 'Ropsten'
const RINKEBY_DISPLAY_NAME = 'Rinkeby'
const KOVAN_DISPLAY_NAME = 'Kovan'
const MAINNET_DISPLAY_NAME = 'Main Ethereum Network'
const GOERLI_DISPLAY_NAME = 'Goerli'
const TOMO_MAINNET_DISPLAY_NAME = 'Main TomoChain Network'
const TOMO_TESTNET_DISPLAY_NAME = 'Test TomoChain Network'

module.exports = {
  ROPSTEN,
  RINKEBY,
  KOVAN,
  MAINNET,
  LOCALHOST,
  GOERLI,
  TOMO_MAINNET,
  TOMO_TESTNET,
  MAINNET_CODE,
  ROPSTEN_CODE,
  RINKEBY_CODE,
  KOVAN_CODE,
  GOERLI_CODE,
  TOMO_MAINNET_CODE,
  TOMO_TESTNET_CODE,
  ROPSTEN_DISPLAY_NAME,
  RINKEBY_DISPLAY_NAME,
  KOVAN_DISPLAY_NAME,
  MAINNET_DISPLAY_NAME,
  GOERLI_DISPLAY_NAME,
  TOMO_MAINNET_DISPLAY_NAME,
  TOMO_TESTNET_DISPLAY_NAME
}
